spring:
  aop:
    auto: false #启动aop配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.110:3306/madio
    username: root
    password: ENC(Z4t2i59nn4i52XCyjdERwyYNu3zNTmKwiWEC9I1dfRWz9qygy86vKHNGuBFBOMuk)
mybatis:
  mapper-locations: classpath:com.example.easyexcel.mapper/*.xml
jasypt:
  encryptor:
    #这里可以理解成是加解密的时候使用的密钥
    password: madio1992