spring:
  aop:
    auto: false #启动aop配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/madio
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:com.example.easyexcel.mapper/*.xml
